/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tours: Tour;
    pages: Page;
    events: Event;
    messages: Message;
    requests: Request;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tours: ToursSelect<false> | ToursSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    requests: RequestsSelect<false> | RequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    footer: Footer;
    contact: Contact;
    costs: Cost;
    'opening-hours': OpeningHour;
    banner: Banner;
    header: Header;
  };
  globalsSelect: {
    footer: FooterSelect<false> | FooterSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    costs: CostsSelect<false> | CostsSelect<true>;
    'opening-hours': OpeningHoursSelect<false> | OpeningHoursSelect<true>;
    banner: BannerSelect<false> | BannerSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Dieser Text wird für Suchmaschinen und Menschen mit Sehbehinderungen benötigt.
   */
  alt?: string | null;
  /**
   * Dieser Text wird unter dem Bild angezeigt.
   */
  caption?: string | null;
  imagekit?: {
    fileId?: string | null;
    thumbnailUrl?: string | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Der Untertitel wird unter dem Titel angezeigt und ist optional.
   */
  subtitle?: string | null;
  /**
   * Die Beschreibung gibt einen kurzen Überblick über die Führung und sollte nicht länger als 2 Sätze sein.
   */
  description: string;
  /**
   * Dieses Bild wird sowohl auf der Führungsseite als auch auf der Übersichtsseite angezeigt.
   */
  image: string | Media;
  /**
   * Die Bildunterschrift wird unter dem Bild angezeigt und ist optional.
   */
  caption?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Die Bildergalerie wird unter dem Inhalt angezeigt und ist optional.
   */
  images?: (string | Media)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * Das Design der Seite legt fest, welcher Inhalt angezeigt wird und sollte auf die jeweilige Seite angepasst werden.
   */
  layout: 'title' | 'title-subtitle-description' | 'home' | 'contact';
  title: string;
  /**
   * Der Untertitel wird unter dem Titel angezeigt.
   */
  subtitle?: string | null;
  /**
   * Die Beschreibung wird unter dem Untertitel angezeigt.
   */
  description?: string | null;
  /**
   * Der Slug wird verwendet, um die Seite zu identifizieren.
   */
  slug: string;
  content?:
    | (
        | ToursBlock
        | RichTextBlock
        | RichTextWithTwoColumnsBlock
        | RichTextWithGalleryBlock
        | TwoColumnsWithImageBlock
        | OneColumnWithImageBlock
        | TextWithTwoImagesBlock
        | StatisticsBlock
        | GalleryBlock
        | CostsBlock
        | DirectionsBlock
        | EventsBlock
        | OpeningHoursBlock
        | TimelineBlock
        | OfferOverviewBlock
        | TextWithSidebarBlock
        | ContactFormBlock
        | BookingFormBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ToursBlock".
 */
export interface ToursBlock {
  title: string;
  description: string;
  dark?: boolean | null;
  /**
   * Wählen Sie alle Führungen aus, die in der Liste angezeigt werden sollen.
   */
  tours: (string | Tour)[];
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tours';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextWithTwoColumnsBlock".
 */
export interface RichTextWithTwoColumnsBlock {
  left: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  right: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richTextWithTwoColumns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextWithGalleryBlock".
 */
export interface RichTextWithGalleryBlock {
  title: string;
  description?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  groups?:
    | {
        title?: string | null;
        images: (string | Media)[];
        id?: string | null;
      }[]
    | null;
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richTextWithGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnsWithImageBlock".
 */
export interface TwoColumnsWithImageBlock {
  title: string;
  description: string;
  content: string;
  image: string | Media;
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'twoColumnsWithImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OneColumnWithImageBlock".
 */
export interface OneColumnWithImageBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image: string | Media;
  buttons?:
    | {
        label: string;
        link: string;
        theme: 'primary' | 'secondary';
        id?: string | null;
      }[]
    | null;
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'oneColumnWithImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextWithTwoImagesBlock".
 */
export interface TextWithTwoImagesBlock {
  title: string;
  description: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  buttons?:
    | {
        label: string;
        link: string;
        theme: 'primary' | 'secondary';
        id?: string | null;
      }[]
    | null;
  images: (string | Media)[];
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textWithTwoImages';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatisticsBlock".
 */
export interface StatisticsBlock {
  title: string;
  description: string;
  statistics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  buttons?:
    | {
        label: string;
        link: string;
        theme: 'primary' | 'secondary';
        id?: string | null;
      }[]
    | null;
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statistics';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  title: string;
  description?: string | null;
  images: (string | Media)[];
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CostsBlock".
 */
export interface CostsBlock {
  title: string;
  description?: string | null;
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'costs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DirectionsBlock".
 */
export interface DirectionsBlock {
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  buttons?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'directions';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsBlock".
 */
export interface EventsBlock {
  title: string;
  description?: string | null;
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'events';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OpeningHoursBlock".
 */
export interface OpeningHoursBlock {
  /**
   * Wenn diese Option aktiviert ist, wird eine Schaltfläche zum Burgplan angezeigt. Der Benutzer kann diesen Plan dann öffnen.
   */
  showImage?: boolean | null;
  image?: (string | null) | Media;
  /**
   * Das Layout bestimmt die Anordnung der Öffnungszeiten.
   */
  layout?: ('horizontal' | 'vertical') | null;
  /**
   * Die Öffnungszeiten bekommen einen grauen Hintergrund, wenn diese Option aktiviert ist.
   */
  background?: boolean | null;
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'opening-hours';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  description?: string | null;
  items?:
    | {
        year?: number | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfferOverviewBlock".
 */
export interface OfferOverviewBlock {
  title: string;
  subtitle: string;
  description: string;
  offers: {
    image: string | Media;
    title: string;
    url: string;
    description: string;
    id?: string | null;
  }[];
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'offer-overview';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextWithSidebarBlock".
 */
export interface TextWithSidebarBlock {
  title: string;
  description: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  sidebar: OpeningHoursBlock[];
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'text-with-sidebar';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  title: string;
  description: string;
  sidebar: OpeningHoursBlock[];
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact-form';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BookingFormBlock".
 */
export interface BookingFormBlock {
  title: string;
  description: string;
  /**
   * Wenn dieser Haken gesetzt ist, wird der Inhalt als Unterpunkt im Menü angezeigt.
   */
  showInSubMenu?: boolean | null;
  /**
   * Der Titel des Unterpunkts wird im Menü angezeigt.
   */
  subMenuTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'booking-form';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  /**
   * Dieses Datum dient der Sortierung und wird nicht in der Liste angezeigt.
   */
  date: string;
  /**
   * Wenn nicht veröffentlicht, wird die Veranstaltung nicht in der Liste angezeigt.
   */
  published?: boolean | null;
  title: string;
  /**
   * Optionaler Link zur Veranstaltung. Falls angegeben wird eine Schaltfläche unter dem Titel angezeigt.
   */
  url?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Der Zeitraum wird links in der Liste angezeigt.
   */
  displayedDate: string;
  /**
   * Die Uhrzeit wird unter dem Zeitraum angezeigt und ist optional.
   */
  time?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  subject: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests".
 */
export interface Request {
  id: string;
  name: string;
  email: string;
  type?: string | null;
  participants: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'tours';
        value: string | Tour;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'requests';
        value: string | Request;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  imagekit?:
    | T
    | {
        fileId?: T;
        thumbnailUrl?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  subtitle?: T;
  description?: T;
  image?: T;
  caption?: T;
  content?: T;
  images?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  layout?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  slug?: T;
  content?:
    | T
    | {
        tours?: T | ToursBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        richTextWithTwoColumns?: T | RichTextWithTwoColumnsBlockSelect<T>;
        richTextWithGallery?: T | RichTextWithGalleryBlockSelect<T>;
        twoColumnsWithImage?: T | TwoColumnsWithImageBlockSelect<T>;
        oneColumnWithImage?: T | OneColumnWithImageBlockSelect<T>;
        textWithTwoImages?: T | TextWithTwoImagesBlockSelect<T>;
        statistics?: T | StatisticsBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        costs?: T | CostsBlockSelect<T>;
        directions?: T | DirectionsBlockSelect<T>;
        events?: T | EventsBlockSelect<T>;
        'opening-hours'?: T | OpeningHoursBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        'offer-overview'?: T | OfferOverviewBlockSelect<T>;
        'text-with-sidebar'?: T | TextWithSidebarBlockSelect<T>;
        'contact-form'?: T | ContactFormBlockSelect<T>;
        'booking-form'?: T | BookingFormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ToursBlock_select".
 */
export interface ToursBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  dark?: T;
  tours?: T;
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextWithTwoColumnsBlock_select".
 */
export interface RichTextWithTwoColumnsBlockSelect<T extends boolean = true> {
  left?: T;
  right?: T;
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextWithGalleryBlock_select".
 */
export interface RichTextWithGalleryBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  groups?:
    | T
    | {
        title?: T;
        images?: T;
        id?: T;
      };
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnsWithImageBlock_select".
 */
export interface TwoColumnsWithImageBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  image?: T;
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OneColumnWithImageBlock_select".
 */
export interface OneColumnWithImageBlockSelect<T extends boolean = true> {
  content?: T;
  image?: T;
  buttons?:
    | T
    | {
        label?: T;
        link?: T;
        theme?: T;
        id?: T;
      };
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextWithTwoImagesBlock_select".
 */
export interface TextWithTwoImagesBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  buttons?:
    | T
    | {
        label?: T;
        link?: T;
        theme?: T;
        id?: T;
      };
  images?: T;
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatisticsBlock_select".
 */
export interface StatisticsBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  statistics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  content?: T;
  buttons?:
    | T
    | {
        label?: T;
        link?: T;
        theme?: T;
        id?: T;
      };
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  images?: T;
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CostsBlock_select".
 */
export interface CostsBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DirectionsBlock_select".
 */
export interface DirectionsBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  buttons?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsBlock_select".
 */
export interface EventsBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OpeningHoursBlock_select".
 */
export interface OpeningHoursBlockSelect<T extends boolean = true> {
  showImage?: T;
  image?: T;
  layout?: T;
  background?: T;
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  description?: T;
  items?:
    | T
    | {
        year?: T;
        content?: T;
        id?: T;
      };
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfferOverviewBlock_select".
 */
export interface OfferOverviewBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  offers?:
    | T
    | {
        image?: T;
        title?: T;
        url?: T;
        description?: T;
        id?: T;
      };
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextWithSidebarBlock_select".
 */
export interface TextWithSidebarBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  sidebar?:
    | T
    | {
        'opening-hours'?: T | OpeningHoursBlockSelect<T>;
      };
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock_select".
 */
export interface ContactFormBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  sidebar?:
    | T
    | {
        'opening-hours'?: T | OpeningHoursBlockSelect<T>;
      };
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BookingFormBlock_select".
 */
export interface BookingFormBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  showInSubMenu?: T;
  subMenuTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  date?: T;
  published?: T;
  title?: T;
  url?: T;
  description?: T;
  displayedDate?: T;
  time?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests_select".
 */
export interface RequestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  type?: T;
  participants?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  footerMenu: (string | Page)[];
  /**
   * Die Bilder werden über der Fußzeile angezeigt. Es müssen genau 6 Bilder ausgewählt werden.
   */
  image: (string | Media)[];
  /**
   * Dies ist in der Regel der Name der Seite.
   */
  title: string;
  /**
   * Die Beschreibung sollte nicht mehr als 1 Satz lang sein und gibt einen kurzen Überblick über die Burgruine.
   */
  description: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: string;
  name: string;
  location: string;
  phone: string;
  email: string;
  social?: {
    instagram?: string | null;
    facebook?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "costs".
 */
export interface Cost {
  id: string;
  items?:
    | {
        title: string;
        price: string;
        /**
         * Diese Beschreibung ist optional und wird unter der Bezeichnung und dem Preis angezeigt.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opening-hours".
 */
export interface OpeningHour {
  id: string;
  titleInnerWard: string;
  notesInnerWard?: string | null;
  titleOuterWard: string;
  notesOuterWard?: string | null;
  exceptions?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner".
 */
export interface Banner {
  id: string;
  showOpeningHours?: boolean | null;
  /**
   * Dieser Text wird in der linken Seite des Banners angezeigt, wenn der Haken nicht gesetzt ist.
   */
  leftSideText?: string | null;
  showNextEvent?: boolean | null;
  /**
   * Dieser Text wird in der rechten Seite des Banners angezeigt, wenn der Haken nicht gesetzt ist.
   */
  rightSideText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  mainMenu: (string | Page)[];
  /**
   * Dieses Bild wird als Hauptbild im Kopfbereich der Seite angezeigt.
   */
  image: string | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  footerMenu?: T;
  image?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  phone?: T;
  email?: T;
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "costs_select".
 */
export interface CostsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        title?: T;
        price?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opening-hours_select".
 */
export interface OpeningHoursSelect<T extends boolean = true> {
  titleInnerWard?: T;
  notesInnerWard?: T;
  titleOuterWard?: T;
  notesOuterWard?: T;
  exceptions?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner_select".
 */
export interface BannerSelect<T extends boolean = true> {
  showOpeningHours?: T;
  leftSideText?: T;
  showNextEvent?: T;
  rightSideText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  mainMenu?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}